language: node_js
node_js:
  # we recommend testing addons with the same minimum supported node version as Ember CLI
  # so that your addon works for all apps
  - "8"

sudo: false
dist: trusty

addons:
  chrome: stable

cache:
  directories:
    - $HOME/.npm

env:
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=1

branches:
  only:
    - master
    # npm version tags
    - /^v\d+\.\d+\.\d+/

jobs:
  fail_fast: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-canary
  env:
    global:
      # See https://git.io/vdao3 for details.
      - JOBS=1
  include:
    # runs linting and tests with current locked deps
    - stage: 'Tests'
      env: EMBER_TRY_SCENARIO=ember-lts-3.4
      env: EMBER_TRY_SCENARIO=ember-lts-3.4-legacy-decorators
    - env: EMBER_TRY_SCENARIO=ember-release
    - env: EMBER_TRY_SCENARIO=ember-release-legacy-decorators
    - env: EMBER_TRY_SCENARIO=ember-beta
    - env: EMBER_TRY_SCENARIO=ember-beta-legacy-decorators
    - env: EMBER_TRY_SCENARIO=ember-canary
    - env: EMBER_TRY_SCENARIO=ember-canary-legacy-decorators
    - env: EMBER_TRY_SCENARIO=ember-default
    - env: EMBER_TRY_SCENARIO=ember-default-legacy-decorators
    - name: 'Blueprints'
      script: yarn nodetest

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - yarn install --no-lockfile --non-interactive

script:
  - yarn lint:js
  # Usually, it's ok to finish the test scenario without reverting
  #  to the addon's original dependency state, skipping "cleanup".
  - node_modules/.bin/ember try:one $EMBER_TRY_SCENARIO --skip-cleanup
